btn_style = (
    "QPushButton{"
    "background-color: rgba(36, 33, 35, 153);"
    "padding: 20px;"
    "font-size: 18px;"
    "letter-spacing: 2px;"
    "color: white;"
    "}"
    "QPushButton:hover{"
    "background-color: rgba(36, 33, 35, 204);"
    "}"
    "QPushButton:pressed{"
    "background-color: rgba(36, 33, 35, 242);"
    "color: rgb(220, 220, 220);"
    "}"
)
 
selectlist_style = (
    "QComboBox {"
    "background-color: rgba(36, 33, 35, 153);"
    "padding: 20px;"
    "font-size: 18px;"
    "letter-spacing: 2px;"
    "color: white;"
    "border: none;"
    "}"
    "QComboBox:hover {"
    "background-color: rgba(36, 33, 35, 204);"
    "}"
    "QComboBox::drop-down {"
    "border: none;"
    "width: 40px;"
    "}"
    "QComboBox::down-arrow {"
    "image: url('arrow.png');"
    "width: 16px;"
    "height: 16px;"
    "}"
    "QComboBox QAbstractItemView {"
    "background-color: rgba(36, 33, 35, 230);"
    "color: white;"
    "selection-background-color: rgba(180, 50, 50, 200);"
    "selection-color: white;"
    "border: 1px solid rgba(255,255,255,30);"
    "padding: 5px;"
    "}"
)